name: Laravel Integrations

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('laravel/.env') || copy('laravel/.env.example', 'laravel/.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      working-directory: laravel
    - name: Generate key
      run: php artisan key:generate
      working-directory: laravel
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      working-directory: laravel
    - name: run test
      run: |
        php artisan test
      working-directory: laravel
